### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by andrewrobertmadsen** [jwills/dbt-duckdb#1]
Super excited about this project. I love duckdb and tying it in with dbt is a great idea. I tried pip installing this package per the readme but a version on Pypi couldn't be found. Has it been published to Pypi yet?

**Comment by jwills** [comment]
Hey Andrew, thanks so much for the note! So I haven't made it available yet b/c there isn't a released version of duckdb that this works with yet-- you have to do a build from source against `duckdb/master` and you would also need these two PRs (which should hopefully be merged in soon!)

https://github.com/cwida/duckdb/pull/1044
https://github.com/cwida/duckdb/pull/1037

...once those are in and a new release of duckdb is cut, I will publish this to Pypi and update the docs to that effect.

**Comment by andrewrobertmadsen** [comment]
Thanks for the context! Want me to leave this open until that happens? or close this provided your context?

**Comment by jwills** [comment]
I'm hoping it won't be that long till the next release, so let's leave it open for now. Thanks again!

**Comment by jwills** [comment]
Fixed now; `pip install dbt-duckdb` does the right thing.
