### ISSUE TITLE
Support PyArrow Dataset as a valid return type for Python models

### ISSUE THREAD

**Issue by davidgasquez** [jwills/dbt-duckdb#119]
From [the docs](https://arrow.apache.org/docs/python/dataset.html): 

> The `pyarrow.dataset` module provides functionality to efficiently work with tabular, potentially larger than memory, and multi-file datasets.

Since `pyarrow.table` type won't work with larger than memory datasets, this might be a good alternative. I was also thinking about Polars but wanted to check first if this was easier to implement.

**Comment by jwills** [comment]
Hrm, it's possible that after @AlexanderVR's most recent PR, this will (almost) just work? We may need to generalize [this check](https://github.com/jwills/dbt-duckdb/blob/master/dbt/include/duckdb/macros/adapters.sql#L58) to look for `pyarrow.dataset.Dataset` as well?

**Comment by davidgasquez** [comment]
Sweet! It works when installing `dbt-duckdb` from GitHub. Thanks a lot @jwills!
