### ISSUE TITLE
The model location config doesn't work as documented

### ISSUE THREAD

**Issue by sacundim** [jwills/dbt-duckdb#227]
The [current README](https://github.com/jwills/dbt-duckdb/blob/796fe97d93a272370be7e9d4b8627ca2b88d8c5b/README.md), as written, at the very least strongly implies that one may use a template to generate the names of the output external files using template variable expansions like `{{ name }}` and `{{ format }}`:

> | Option | Default | Description
> | :---:    |  :---:    | ---
> | location | `{{ name }}.{{ format }}` | The path to write the external materialization to. See below for more details.

...but it doesn't actually work. I tried using for example `{{ name }}-lol.{{ format }}` and it produces files named `-lol.` (the variables expand to empty strings).

**Comment by jwills** [comment]
Yeah, that is unfortunate; jinja expansion does work inside of the `location` string, it's just that neither `name` nor `format` are variables in the context that jinja has access to (the equivalent of `{{ name }}` here would be e.g. `{{ this.identifier }}`.)

I'll post a PR to remove the implication.
