### ISSUE TITLE
Give a duck some ❤️

### ISSUE THREAD

**Issue by tomsej** [jwills/dbt-duckdb#26]
Ducks are fantastic animals but need some care, just like a code. [Here](https://github.com/dbt-labs/dbt-database-adapter-scaffold) is a repository for scaffolding dbt adapter. Unfortunately, this awesome project does not comply to that, which makes contribution more challenging than it has to be.

Would it be okay if I brought the structure closer to the template?

**Comment by jwills** [comment]
Hey @tomsej! I haven't seen that scaffolding repo before-- where is it used? And how does it work?

**Comment by tomsej** [comment]
Think the repo is used in all the main adapter repositories like [dbt-spark](https://github.com/dbt-labs/dbt-spark) or [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake). It is a [cookiecutter](https://github.com/cookiecutter/cookiecutter) template. So at the beginning of the development you just run `cookiecutter gh:dbt-labs/dbt-database-adapter-scaffold` and it scaffolds project structure for you. But now, when project is already up, it would be better just to copy some content.

There are some particular paint points that are solved in cookiecutter:
- missing `dev-requirements.txt`, so you need to find required dev dependencies yourself.
- missing tox configuration and github actions configuration. So testing on multiple python version is harder.
- semantic versioning of the package.

**Comment by jwills** [comment]
Ah, gotcha-- I would welcome the changes needed to support this via a PR, thanks!
