### ISSUE TITLE
Python models

### ISSUE THREAD

**Issue by tomsej** [jwills/dbt-duckdb#27]
It would be great to have a support for dbt Python Models. My use case is primarily to read/write into Delta tables (hope it will be obsolete with [duckdb-deltatable-extension](https://github.com/Mause/duckdb-deltatable-extension)), but there are many other possibilities.

I have already created a prototype, but it is an ugly duckling that supports only single thread (which is okish for my use-case). But I do not expect PR to be merged anytime soon.

P.S. I have created this issue because it is always nice to have both PR and issue :)

**Comment by jwills** [comment]
Would love to see the prototype in a PR/branch, even if you don't like it. I haven't settled on a way to implement python models with dbt-duckdb that I like, but I am very open to suggestions.

**Comment by tomsej** [comment]
Sure! Tomorrow I will send it. Need to put my daughter to sleep 😄
