### ISSUE TITLE
dbt models cannot see each other when using the :memory: database.

### ISSUE THREAD

**Issue by matsonj** [jwills/dbt-duckdb#30]
## Describe the bug
dbt models cannot see each other when using the :memory: database.

## To Reproduce

1. create two models. table_one.sql & table_two.sql
2. table_one.sql should be "SELECT 'test' AS value".
3. table_two.sql should be "SELECT * FROM {{ ref( 'table_one' ) }}
4. table_two will fail to build with following error: "Catalog Error: Table with name table_one does not exist"

## Expected behavior
dbt build should succeed.

## Your environment
Version of dbt-duckdb: ~=1.2.0

**Comment by jwills** [comment]
Sorry about that @matsonj -- unfortunate artifact of how I did the multithreading code in a way that kept the fal-ai `PythonAdapter` stuff working. Will be fixed in the next release!
