### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by NathanHowell** [jwills/dbt-duckdb#4]
I'd like to kick the tires on this project but it's not clear what the license is. Can you add one?

fwiw DuckDB is MIT licensed and dbt-core is Apache. A license compatible with both of these would be ideal.

**Comment by jwills** [comment]
Done! Please let me know anything else you find; this is a labor of love for me.

**Comment by NathanHowell** [comment]
thanks for the fast turn around, I'll let ya know what I bump into. first thing will be relaxing the version requirements now that dbt-core is at 1.0.0 :-)
