### ISSUE TITLE
External materialization file paths do not support jinja references

### ISSUE THREAD

**Issue by matsonj** [jwills/dbt-duckdb#55]
Consider the following config block:

```
{{ 
    config(
        materialized='external', 
        location='/path/to/folder/{{ this.name }}.parquet'
) }}
```

This should write the model name to the folder specified.

However, what happens is the name is written literally as ```{{ this.name }}.parquet``` as seen in the screenshot below.

![705B6873-6F32-4976-BDA0-8F527E0E0FE6](https://user-images.githubusercontent.com/16811433/201489661-1c73d2a9-e128-4005-8bd2-accece0fa241.jpeg)

I would expect that the external materialization works with the same syntax as this (but it does not):

```
COPY (SELECT * FROM {{ this }} ) TO '/tmp/data_catalog/conformed/{{ this.name }}.parquet' (FORMAT 'parquet')
```

**Comment by jwills** [comment]
Ah yeah, so the `location` field isn't a jinja template (unlike, say `post_hook`), but we can fix that pretty easily. In the meantime, here's a workaround for you:

```
{% set location = "/tmp/data_catalog/conformed/" ~ this.name ~ ".parquet" %}

{{
    config(
        materialized='external',
        location=location,
) }}
```

**Comment by matsonj** [comment]
Work around (thanks @jwills )

```
{% set location = "/tmp/" ~ this.name ~ ".parquet" %}

{{
    config(
        materialized='external',
        location=location,
) }}
```

**Comment by jwills** [comment]
jinx!

**Comment by matsonj** [comment]
I just tested the following header config which also works:

```
{{ 
    config(
        materialized='external', 
        location="/tmp/data_catalog/conformed/" ~ this.name ~ ".parquet"
) }}
```

Obviously, if the folder does not exist, there is no mechanism to create the folder first, so you need to make sure all your directories exist first.
