### ISSUE TITLE
add adapter to dbt docs's "Available Adapters" page

### ISSUE THREAD

**Issue by dataders** [jwills/dbt-duckdb#6]
howdy @jwills

The [Available Adapters](https://docs.getdbt.com/docs/available-adapters) page is one of the dbt community's most-visited docs pages. It would be of great benefit for first-time visitors to the dbt docs to see:
1. that this adapter is a possible option for using dbt-core, and
2. how many large the dbt ecosystem of support databases is.

https://github.com/dbt-labs/docs.getdbt.com/issues/1489 exists to address this with all as-of-yet undocumented adapters.

We just released [Documenting a new adapter](https://docs.getdbt.com/docs/contributing/documenting-a-new-adapter), a new guide on how to add an adapter to the Available Adapters page. I'd love to see this adapter on that page, so feel free to reach out with any questions/blockers by either replying to this issue, or posting in the #adapter-ecosystem channel of the dbt Community Slack.

Looking forward to the contribution!

**Comment by TylerHillery** [comment]
I was looking for a way to get started in open source and this looked like a good first issue. I hope you don't mind Josh, I went ahead and created a [pull request](https://github.com/dbt-labs/docs.getdbt.com/pull/1610) . Let me know if you have any objections.

**Comment by jwills** [comment]
None whatsoever @TylerHillery - thank you so much! ❤️

**Comment by jwills** [comment]
I think we're good-to-go here, right?

**Comment by TylerHillery** [comment]
Yes, all good here!
