### ISSUE TITLE
Python model fails with import statement outside of function

### ISSUE THREAD

**Issue by grahamwetzler** [jwills/dbt-duckdb#63]
Python models aren't working as I expect. This basic example fails:

```py
import pandas as pd

def model(dbt, session):

    return pd.Series(range(10)).to_frame()
```

```
15:32:53  Runtime Error in model 03 (days/03.py)
15:32:53    Python model failed:
15:32:53    name 'pd' is not defined
```

However, simply moving the import statement into the function allows it to work.
```py
def model(dbt, session):
    import pandas as pd
    return pd.Series(range(10)).to_frame()
```

Versions:
- dbt-duckdb 1.3.2
- dbt 1.3.1
- Python 3.10.7

**Comment by jwills** [comment]
Hey @grahamwetzler thanks for the heads up here; I'm banging my head against this one but haven't solved it yet. It seems like it has something to do with how jinja mucks up the formatting of the Python code before we submit it to `exec`, but I can't figure out how to undo the mucking in a way that lets the `import` block that you define outside of the `def model` function work correctly. Will be curious if @tomsej has any more luck with it. :/
