### ISSUE TITLE
Models that depend on external models do not automatically register their dependencies as views

### ISSUE THREAD

**Issue by AlexanderVR** [jwills/dbt-duckdb#79]
Suppose we specify `+materialization: external` in our dbt_project.yml.

Initially we run all dbt computations using an in-memory db, materializing all the models as parquet files.

Subsequently we change one dbt model A, and want to recompute model A (and possibly downstream dependencies as well).

Now, if A depends on upstream models B and C, trying to run just A will result in a failure. Because, B and C are not registered as views yet (in-memory db!), despite all tables being specified as external. This forces the user to always recompute upstream dependencies just to trigger the registration logic https://github.com/jwills/dbt-duckdb/blob/master/dbt/include/duckdb/macros/materializations/external.sql#L51-L55

I'd like to propose putting in a check in the materialization macros to 
- loop through the parent nodes
- for each parent_node, if load_cached_relation(parent_node) is None, call the registration logic.

Does this sound reasonable? Happy to send a PR.

**Comment by jwills** [comment]
The problem as you describe it makes sense, but I still don't totally grok the use case where folks are running stuff entirely in-memory over-and-over again without using a DuckDB database file, even if it's just to keep track of view definitions and how they map to external parquet files. Where does this sort of thing come up?

**Comment by AlexanderVR** [comment]
Suppose you have a `dbt` graph containing several hundred models. Different sets of sources are updated at different times (or one might update a few model definitions), and you spin off Kubernetes jobs that recompute the affected subsets of the graph.

With a centralized DuckDB database file, you would need some locking mechanism allowing only one job at a time to take ownership of the DuckDB file. 

There is also the temporary instability of the DuckDB storage format, which makes sharing the db files across different jobs with possibly different DuckDB versions a bit annoying.

**Comment by jwills** [comment]
yes, got it-- thank you so much for taking the time to explain it! A PR would be most welcome!
