### ISSUE TITLE
Most recent releases missing from Github

### ISSUE THREAD

**Issue by droher** [jwills/dbt-duckdb#81]
The most recent release on Github is 1.3.1, but pypi is up to 1.3.4: https://pypi.org/project/dbt-duckdb/
Not sure if intentional but wanted to flag in case it wasn't. Thanks so much for this package, it's incredibly useful!

**Comment by jwills** [comment]
Ah, not intentional-- will get it fixed up tomorrow or Monday, thanks!

**Comment by jwills** [comment]
Been meaning to fix this for awhile-- dbt-duckdb 1.4.0 is now up on the releases tab
